---
- name: Deploy App
  hosts: web
  become: yes

  tasks:

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop old containers
      shell: docker stop nginx nodeapp mongodb 2>/dev/null || true

    - name: Remove old containers
      shell: docker rm nginx nodeapp mongodb 2>/dev/null || true

    - name: Run MongoDB
      shell: docker run -d --name mongodb --restart always -p 27017:27017 mongo:6

    - name: Wait MongoDB
      pause:
        seconds: 10

    - name: Create app folder
      file:
        path: /home/ec2-user/app
        state: directory

    - name: Write server.js
      copy:
        dest: /home/ec2-user/app/server.js
        content: |
          var express = require('express');
          var app = express();
          app.get('/', function(req, res) {
            res.send('<h1>E-Commerce Store</h1><p>Laptop 1200</p><p>Phone 800</p>');
          });
          app.listen(3000);

    - name: Write package.json
      copy:
        dest: /home/ec2-user/app/package.json
        content: |
          {"name":"app","version":"1.0.0","dependencies":{"express":"4.18.2"}}

    - name: Run Node app
      shell: |
        docker run -d \
          --name nodeapp \
          --restart always \
          -p 3000:3000 \
          -v /home/ec2-user/app:/app \
          -w /app \
          node:18-alpine \
          sh -c "npm install && node server.js"

    - name: Write nginx.conf
      copy:
        dest: /home/ec2-user/nginx.conf
        content: |
          events {}
          http {
            server {
              listen 80;
              location / {
                proxy_pass http://172.17.0.1:3000;
              }
            }
          }

    - name: Run Nginx
      shell: |
        docker run -d \
          --name nginx \
          --restart always \
          -p 80:80 \
          -v /home/ec2-user/nginx.conf:/etc/nginx/nginx.conf \
          nginx:alpine

    - name: Check containers
      shell: docker ps
      register: result

    - name: Show containers
      debug:
        msg: "{{ result.stdout }}"
